name: Daily Price Tracker

on:
  # schedule:
    # - cron: "0 6 * * *"  # every day at 06:00 UTC (~09:00 BG)
  workflow_dispatch:       # allows manual run

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run price tracker
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python tracker.py
